import os

from app.config import GROQ_API_KEY, get_user_repos_path
from app.graph.graph_builder import load_graph
from app.graph.graph_queries import get_file_summary
from app.llm.architecture_summarizer import summarize_architecture



def generate_readme(repo_name: str, user_id: str) -> dict:
    from groq import Groq
    client = Groq(api_key=GROQ_API_KEY)
    G = load_graph(repo_name, user_id=user_id)

    file_nodes = [n for n, d in G.nodes(data=True) if d.get("type") == "file"]
    parsed_files = [{"language": G.nodes[n].get("language", ""), "file_path": n} for n in file_nodes]

    architecture = summarize_architecture(repo_name, G, parsed_files)

    readme = f"""# {repo_name}

## Architecture Overview
{architecture}

## Project Structure
- Total files analyzed: {len(file_nodes)}
- Graph nodes: {G.number_of_nodes()}
- Graph edges: {G.number_of_edges()}

## Getting Started
> This README was auto-generated by Codebase Intel.
"""

    os.makedirs("app/data/docs", exist_ok=True)
    output_path = f"app/data/docs/{repo_name}_README.md"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(readme)

    return {"repo_name": repo_name, "readme": readme, "saved_to": output_path}


def generate_function_docs(repo_name: str, file_path: str, user_id: str) -> dict:
    from groq import Groq
    client = Groq(api_key=GROQ_API_KEY)
    G = load_graph(repo_name, user_id=user_id)
    summary = get_file_summary(G, file_path)
    docs = []

    for func in summary["functions"]:
        full_path = os.path.join(get_user_repos_path(user_id), repo_name, file_path)
        code_snippet = ""
        try:
            with open(full_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
            lines = content.split("\n")
            for i, line in enumerate(lines):
                if f"def {func}" in line or f"function {func}" in line:
                    code_snippet = "\n".join(lines[i:i+10])
                    break
        except Exception:
            pass

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": "Write a concise docstring for this function. Return only the docstring text, no code."},
                {"role": "user", "content": f"Function: {func}\nCode:\n{code_snippet}"}
            ],
            temperature=0.2,
            max_tokens=200
        )
        docs.append({
            "function": func,
            "docstring": response.choices[0].message.content.strip()
        })

    return {"file": file_path, "functions_documented": len(docs), "docs": docs}